const COUNT_REQUEST = "COUNT_REQUEST";
const COUNT_SUCCESS = "COUNT_SUCCESS";
const COUNT_FAILED = "COUNT_FAILED";
const PAGINATION_REQUEST = "PAGINATION_REQUEST";
const PAGINATION_SUCCESS = "PAGINATION_SUCCESS";
const PAGINATION_FAILED   = "PAGINATION_FAILED";
const UPDATE_REQUEST ="UPDATE_REQUEST";
const UPDATE_SUCCESS="UPDATE_SUCCESS";
const UPDATE_FAILED= "UPDATE_FAILED";


export {

    COUNT_REQUEST,
    COUNT_SUCCESS,
    COUNT_FAILED,
    PAGINATION_REQUEST,
    PAGINATION_SUCCESS,
    PAGINATION_FAILED,
    UPDATE_REQUEST,
    UPDATE_SUCCESS,
    UPDATE_FAILED



}