const COUNT_REQUEST = "COUNT_REQUEST";
const COUNT_SUCCESS = "COUNT_SUCCESS";
const COUNT_FAILED = "COUNT_FAILED";
const PAGINATION_REQUEST = "PAGINATION_REQUEST";
const PAGINATION_SUCCESS = "PAGINATION_SUCCESS";
const PAGINATION_FAILED   = "PAGINATION_FAILED";


export {

    COUNT_REQUEST,
    COUNT_SUCCESS,
    COUNT_FAILED,
    PAGINATION_REQUEST,
    PAGINATION_SUCCESS,
    PAGINATION_FAILED


}