const OTP_REQUEST = "OTP_REQUEST";
const OTP_SUCCESS = "OTP_SUCCESS";
const OTP_NOT_FOUND = "OTP_NOT_FOUND";
const VERIFY_REQUEST = "VERIFY_REQUEST";
const VERIFY_SUCCESS = "VERIFY_SUCCESS";
const VERIFY_FAILED = "VERIFY_FAILED";


export {
    
    OTP_REQUEST,
    OTP_SUCCESS,
    OTP_NOT_FOUND,
    VERIFY_REQUEST,
    VERIFY_SUCCESS,
    VERIFY_FAILED



}