const COUNT_REQUEST = "COUNT_REQUEST";
const COUNT_SUCCESS = "COUNT_SUCCESS";
const COUNT_FAILED = "COUNT_FAILED";
const COUNT_PENDING_REQUEST = "COUNT_PENDING_REQUEST";
const COUNT_PENDING_SUCCESS = "COUNT_PENDING_SUCCESS";
const COUNT_PENDING_FAILED = "COUNT_PENDING_FAILED";
const COUNT_TOTAL_REQUEST = "COUNT_TOTAL_REQUEST";
const COUNT_TOTAL_SUCCESS = "COUNT_TOTAL_SUCCESS";
const COUNT_TOTAL_FAILED ="COUNT_TOTAL_FAILED";


export {

    COUNT_REQUEST,
    COUNT_SUCCESS,
    COUNT_FAILED,
    COUNT_PENDING_REQUEST,
    COUNT_PENDING_SUCCESS,
    COUNT_PENDING_FAILED,
    COUNT_TOTAL_REQUEST,
    COUNT_TOTAL_SUCCESS,
    COUNT_TOTAL_FAILED



}